substitutions:
  name: "simple-assist-sensor"
  friendly_name: "Simple Assist"
  project_name: "fabio-garavini.simple-assist-push-to-talk"
  project_version: "1.0.2"
  assist_noise_suppression_level: "1"
  assist_auto_gain: 0dBFS
  assist_volume_multiplier: "15"
  log_level: "ERROR"

dashboard_import:
  package_import_url: github://fabio-garavini/Xiao-Sense_Assist_ESPHome/simple-assist-push-to-talk.yaml@main
  import_full_config: false

packages:
  device_base: github://fabio-garavini/Xiao-Sense_Assist_ESPHome/common/xiao-esp32s3-esp-idf-base.yaml@main
  internal-microphone: github://fabio-garavini/Xiao-Sense_Assist_ESPHome/common/internal-microphone.yaml@main
  assist_base: github://fabio-garavini/Xiao-Sense_Assist_ESPHome/common/assist-base.yaml@main

#wifi:                      # <-- Uncomment this if you want to manually setup wifi credentials
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password