esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version} 
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio
    board_build.f_cpu: 240000000L
    board_upload.maximum_ram_size: 327680
    board_upload.maximum_size: 8388608

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  flash_size: 8MB

logger:
  level: ${log_level}

api:

ota:

wifi:
  ap:

captive_portal:

psram:
  mode: octal
  speed: 80MHz