esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ${project_name}
    version: ${project_version}

esp32:
  board: esp32s3box
  variant: esp32s3
  flash_size: 8MB
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0

logger:
  level: ${log_level}

api:

ota:

wifi:
  ap:

captive_portal:

psram:
  mode: octal
  speed: 80MHz